title: GopenPGP
description: An easy-to-use OpenPGP wrapper library written in golang
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  library: https://github.com/ProtonMail/crypto
  wrapper: https://github.com/ProtonMail/gopenpgp