title: GopenPGP
description: Supplementary Go cryptography libraries
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  library: https://github.com/ProtonMail/crypto
  wrapper: https://github.com/ProtonMail/gopenpgp